### ISSUE TITLE
Criar 5w2h

### ISSUE THREAD

**Issue by FellipeV540** [Projetos-de-Extensao/PBE_24.2_8001_IV_HighlightHub#1]
- [x] Definir Tema do Aplicativo
- [x] Selecione as 3 principais funcionalidades
- [x] Documento 5W2H

**Comment by jp-abdu** [comment]
- [x] Definir Tema do Aplicativo
(Melhores momentos do esporte)
- [x] Selecionar as 3 principais funcionalidades
(-streaming de videos sobre esporte; -streaming de audio; -filtragem por esporte)

**Comment by FellipeV540** [comment]
Documento 5W2H autalizado.
